### ISSUE TITLE
Precompile the package?

### ISSUE THREAD

**Issue by sglyon** [lobingera/Rsvg.jl#12]
Could the Rsvg module be precompiled?

**Comment by lobingera** [comment]
Yes. But the observable performance gain is limited, as Rsvg.jl is only a very thin layer i.e, function header + ccall to the (compiled) code in the library.

**Comment by sglyon** [comment]
I see.

This is actually causing problems downstream. I would like to precompile PlotlyJS - which loads Rsvg — but cannot because Rsvg is not precompiled.

**Comment by lobingera** [comment]
PR?

**Comment by sglyon** [comment]
Yep, happy to open one. Just wanted to chat in an issue to make sure there wasn’t something you knew of that precluded precompilation from working.

**Comment by davidanthoff** [comment]
This can also be closed, right?
