### ISSUE TITLE
InitError: error compiling __init__: could not load library "~\.julia\v0.6\WinRPM\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin\librsvg-2-2.DLL" The specified module could not be found.

### ISSUE THREAD

**Issue by babaq** [lobingera/Rsvg.jl#19]
Hi,

I have this wired error during init of module Rsvg for a quiet long time on a specific windows 7 machine, I tried update windows, delete and reinstall Julia packages, including Gtk.jl and Cairo.jl, but still not working. On the other hand, the other windows 7 machine works fine without this error.

I have no idea how this come, maybe some system configuration?

I am running Julia 0.6.3, and Rsvg.jl is v0.2.1

**Comment by lobingera** [comment]
Have you checked, if this file is actually existing? Could be a WinRPM issue, if not.

**Comment by babaq** [comment]
yes, the file is sit right in the path.

**Comment by lobingera** [comment]
Can you please provide full output?

**Comment by babaq** [comment]
I tried to narrow down the problem, it seems that load `Rsvg` alone is fine, but loading `Rsvg` after loading `MAT` create the problem. I have `MAT` v0.4.0

![image](https://user-images.githubusercontent.com/92771/42127320-1aaa8f40-7c4b-11e8-8fe4-658f52e641be.png)
