### ISSUE TITLE
Error on MacOS, Julia 1.0

### ISSUE THREAD

**Issue by affans** [lobingera/Rsvg.jl#23]
```
(v1.0) pkg> add Rsvg
 Resolving package versions...
 Installed Rsvg ─ v0.2.1
  Updating `Project.toml`
  [c4c386cf] + Rsvg v0.2.1
  Updating `Manifest.toml`
  [c4c386cf] + Rsvg v0.2.1
  Building Rsvg → `~/.julia/packages/Rsvg/AEdKr/deps/build.log`
┌ Error: Error building `Rsvg`:
│ ERROR: LoadError: LoadError: UndefVarError: is_linux not defined
│ Stacktrace:
│  [1] top-level scope at none:0
│  [2] eval at ./boot.jl:319 [inlined]
│  [3] @static(::LineNumberNode, ::Module, ::Any) at ./osutils.jl:19
│  [4] include at ./boot.jl:317 [inlined]
│  [5] include_relative(::Module, ::String) at ./loading.jl:1038
│  [6] include(::Module, ::String) at ./sysimg.jl:29
│  [7] include(::String) at ./client.jl:388
│  [8] top-level scope at none:0
│ in expression starting at /Users/abmlab/.julia/packages/Rsvg/AEdKr/deps/build.jl:8
│ in expression starting at /Users/abmlab/.julia/packages/Rsvg/AEdKr/deps/build.jl:8
└ @ Pkg.Operations /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1068
```

**Comment by affans** [comment]
The problem was related to `Cairo` which was inherently related to `Homebrew`. Basically Homebrew didn't install `graphite2` so running 
```
shell> brew install graphite2
```
fixed my problem for me.

For more information, see https://github.com/JuliaGraphics/Cairo.jl/issues/230 

I am going to leave this open for now incase someone else is looking to build Rsvg/Cairo on 0.7/1.0 and is facing trouble.

**Comment by chfin** [comment]
I get the same error on Linux. Cairo builds fine for me, but the error messages actually looks like Rsvg's `build.jl` is using `is_linux`, which has been replaced by `Sys.islinux` in 1.0 (giving a warning in 0.7).

Edit: Apparently, this has already been fixed on master, so `]add Rsvg#master` should work until the next release.
