### ISSUE TITLE
Pdf output is blank on Julia 0.6.4 

### ISSUE THREAD

**Issue by gtollefson** [lobingera/Rsvg.jl#28]
Hi, I'm using Rsvg.jl on Julia 0.6.4 and am saving a PlotlyJS.jl graphic in pdf. It saves but the plot only shows axes with no data plotted. 

I think this could be an issue with my Rsvg install, which I've tried to fix below. If it's an issue with PlotlyJS.jl, maybe @sglyon can help.

Here's a reprex using PlotlyJS.jl to plot and Rsvg.jl to export.

```
using PlotlyJS
using Rsvg

function heatmap1()
    plot(heatmap(z=[1 20 30; 20 1 60; 30 60 1]))
end

h = heatmap1()

PlotlyJS.savefig(h, "example_reprex.pdf", js=:remote)
```
outputs:
[example_reprex.pdf](https://github.com/lobingera/Rsvg.jl/files/2828668/example_reprex.pdf)

When I rebuild Rsvg.jl I see 

> julia> Pkg.build("Rsvg")
> INFO: Building Homebrew
> Already up-to-date.
> INFO: Building Cairo
> INFO: Building Rsvg
> Error: No available formula with the name "libgio" 
> Error: No available formula with the name "libgio"

**Comment by lobingera** [comment]
It's an interesting error case, that you get a working pdf, but missing some content. I'm not a plotlyJS user, how do other output formats of this example look like?
The libgio thing looks like (again) a homebrew problem ...

**Comment by gtollefson** [comment]
@lobingera Only html and svg output correctly. eps and pdf both export but appear as empty plots with axes but no data/formatting.

**Comment by gtollefson** [comment]
Libgio does look like a homebrew.jl problem. I'll post there now.

**Comment by sglyon** [comment]
Hey @gtollefson I think we've maybe talked about this before but the julia 0.7+ PlotlyJS savefig functionality is much more robust and comes through https://github.com/sglyon/ORCA.jl, which is a wrapper around plotly's commercial plot export utility orca. 

I realize you are on 0.6 still and that  ORCA.jl doesn't quite work b/c of a backward incompatible change to how subprocesses are spawned in julia 0.6 vs. 0.7. But, it might be a lower cost/effort solution to make a quick patch to ORCA.jl so it works with julia 0.6.

**Comment by gtollefson** [comment]
Hi @sglyon , I am planning on updating my code to be compatible with Julia 0.7/1.0 but am finishing development in 0.6.4 first. I'll update my code to 0.7 and go from there!

**Comment by sglyon** [comment]
Ok, whatever suits you.

i do believe that making ORCA.jl 0.6 compatible is likely a one line of code change ([this line](https://github.com/sglyon/ORCA.jl/blob/1aeb797cf890012236fd41af030b2cb0a9df1e6d/src/ORCA.jl#L83) in particular), so if that is a helpful stopgap until the rest of your code in 0.7+ compatible then I'd accept a PR that makes it work

**Comment by davidanthoff** [comment]
I believe this issue can probably be closed?
