### ISSUE TITLE
Error: Error building `Rsvg`

### ISSUE THREAD

**Issue by cailiangliang765** [lobingera/Rsvg.jl#31]
Julia Version 1.0.3
Platform Info:
  OS: Linux (x86_64-conda_cos6-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 4

┌ Error: Error building `Rsvg`: 
│ ERROR: LoadError: None of the selected providers can install dependency rsvg.
│ Use BinDeps.debug(package_name) to see available providers
│ 
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at /home/cllcentosvm/.julia/packages/BinDeps/ZEval/src/dependencies.jl:949
│  [3] satisfy!(::BinDeps.LibraryDependency) at /home/cllcentosvm/.julia/packages/BinDeps/ZEval/src/dependencies.jl:922
│  [4] top-level scope at /home/cllcentosvm/.julia/packages/BinDeps/ZEval/src/dependencies.jl:977
│  [5] include at ./boot.jl:317 [inlined]
│  [6] include_relative(::Module, ::String) at ./loading.jl:1044
│  [7] include(::Module, ::String) at ./sysimg.jl:29
│  [8] include(::String) at ./client.jl:392
│  [9] top-level scope at none:0
│ in expression starting at /home/cllcentosvm/.julia/packages/Rsvg/uwc9D/deps/build.jl:33
└ @ Pkg.Operations /home/conda/feedstock_root/build_artifacts/julia_1548684429855/work/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1097

**Comment by lobingera** [comment]
Could you please post the output of BinDeps.debug ?

**Comment by cailiangliang765** [comment]
@lobingera Last login: Thu Apr 25 10:04:40 2019 from 192.168.220.1
[cllcentosvm@localhost ~]$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.3
 _/ |\__'_|_|_|\__'_|  |  conda-forge-julia release
|__/                   |

julia> BinDeps.debug("Rsvg")
ERROR: UndefVarError: BinDeps not defined
Stacktrace:
 [1] top-level scope at none:0

julia> using BinDeps
ERROR: ArgumentError: Package BinDeps not found in current path:
- Run `import Pkg; Pkg.add("BinDeps")` to install the BinDeps package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:823

julia> import BinDeps
ERROR: ArgumentError: Package BinDeps not found in current path:
- Run `import Pkg; Pkg.add("BinDeps")` to install the BinDeps package.

Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:823

julia> import Pkg

julia> Pkg.add("BinDeps")
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
  [9e28174c] + BinDeps v0.8.10
  Updating `~/.julia/environments/v1.0/Manifest.toml`
 [no changes]

julia> import BinDeps

julia> BinDeps.debug("Rsvg")
ERROR: UndefVarError: STDOUT not defined
Stacktrace:
 [1] debug(::String) at /home/cllcentosvm/.julia/packages/BinDeps/ZEval/src/debug.jl:69
 [2] top-level scope at none:0

julia> Pkg.build("Rsvg")
  Building LibCURL ─→ `~/.julia/packages/LibCURL/khRkY/deps/build.log`
  Building WinRPM ──→ `~/.julia/packages/WinRPM/Y9QdZ/deps/build.log`
  Building Homebrew → `~/.julia/packages/Homebrew/s09IX/deps/build.log`
  Building Cairo ───→ `~/.julia/packages/Cairo/CXPG1/deps/build.log`
  Building Rsvg ────→ `~/.julia/packages/Rsvg/uwc9D/deps/build.log`
┌ Error: Error building `Rsvg`:
│ ERROR: LoadError: None of the selected providers can install dependency rsvg.
│ Use BinDeps.debug(package_name) to see available providers
│
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at /home/cllcentosvm/.julia/packages/BinDeps/ZEval/src/dependencies.jl:949
│  [3] satisfy!(::BinDeps.LibraryDependency) at /home/cllcentosvm/.julia/packages/BinDeps/ZEval/src/dependencies.jl:922
│  [4] top-level scope at /home/cllcentosvm/.julia/packages/BinDeps/ZEval/src/dependencies.jl:977
│  [5] include at ./boot.jl:317 [inlined]
│  [6] include_relative(::Module, ::String) at ./loading.jl:1044
│  [7] include(::Module, ::String) at ./sysimg.jl:29
│  [8] include(::String) at ./client.jl:392
│  [9] top-level scope at none:0
│ in expression starting at /home/cllcentosvm/.julia/packages/Rsvg/uwc9D/deps/build.jl:33
└ @ Pkg.Operations /home/conda/feedstock_root/build_artifacts/julia_1548684429855/work/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1097

julia> BinDeps.debug("Rsvg")
ERROR: UndefVarError: STDOUT not defined
Stacktrace:
 [1] debug(::String) at /home/cllcentosvm/.julia/packages/BinDeps/ZEval/src/debug.jl:69
 [2] top-level scope at none:0

julia>

**Comment by cailiangliang765** [comment]
> Could you please post the output of BinDeps.debug ?

Hi @lobingera here is the output:
BinDeps.debug(stdout, "Rsvg")

┌ Info: Reading build script...
└ @ BinDeps /home/cllcentosvm/.julia/packages/BinDeps/ZEval/src/debug.jl:48
┌ Warning: `Pkg.dir(pkgname, paths...)` is deprecated; instead, do `import Rsvg; joinpath(dirname(pathof(Rsvg)), "..", paths...)`.
└ @ Pkg.API /home/conda/feedstock_root/build_artifacts/julia_1548684429855/work/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:480
MethodError: no method matching eval(::Module, ::Expr)
You may have intended to import Base.eval
Closest candidates are:
  eval(::Any) at /home/cllcentosvm/.julia/packages/BinDeps/ZEval/src/BinDeps.jl:3

Stacktrace:
 [1] eval_anon_module(::BinDeps.PackageContext, ::String) at /home/cllcentosvm/.julia/packages/BinDeps/ZEval/src/BinDeps.jl:557
 [2] debug_context(::String) at /home/cllcentosvm/.julia/packages/BinDeps/ZEval/src/debug.jl:52
 [3] debug(::IJulia.IJuliaStdio{Base.PipeEndpoint}, ::String) at /home/cllcentosvm/.julia/packages/BinDeps/ZEval/src/debug.jl:57
 [4] top-level scope at In[14]:1

**Comment by asbisen** [comment]
I am experiencing same issue with CentOS 7 based install. Installing librsvg2-devel package fixed the issue. `yum install -y librsvg2-devel`
