### ISSUE TITLE
Error building Rsvg

### ISSUE THREAD

**Issue by gtollefson** [lobingera/Rsvg.jl#34]
I receive the following error when trying to build Rsvg.jl on Julia 1.1.0 on a Macbook pro running High Sierra 10.13.6. Can you help me solve this? We're in the final stage of a development project so it's rather urgent.

The error I receive is:

> ERROR: LoadError: LoadError: LoadError: Unable to load 
> 
> librsvg (/Users/George/.julia/packages/Homebrew/s09IX/deps/usr/lib/librsvg-2.2.dylib)
> 
> Please re-run Pkg.build(package), and restart Julia.
> Stacktrace:
>  [1] error(::String, ::String) at ./error.jl:42
>  [2] @checked_lib(::LineNumberNode, ::Module, ::Any, ::Any) at /Users/George/.julia/packages/Rsvg/uwc9D/deps/deps.jl:11
>  [3] include at ./boot.jl:326 [inlined]
>  [4] include_relative(::Module, ::String) at ./loading.jl:1038
>  [5] include at ./sysimg.jl:29 [inlined]
>  [6] include(::String) at /Users/George/.julia/packages/Rsvg/uwc9D/src/Rsvg.jl:2
>  [7] top-level scope at none:0
>  [8] include at ./boot.jl:326 [inlined]
>  [9] include_relative(::Module, ::String) at ./loading.jl:1038
>  [10] include(::Module, ::String) at ./sysimg.jl:29
>  [11] top-level scope at none:2
>  [12] eval at ./boot.jl:328 [inlined]
>  [13] eval(::Expr) at ./client.jl:404
>  [14] top-level scope at ./none:3
> in expression starting at /Users/George/.julia/packages/Rsvg/uwc9D/deps/deps.jl:21
> in expression starting at /Users/George/.julia/packages/Rsvg/uwc9D/deps/deps.jl:21
> in expression starting at /Users/George/.julia/packages/Rsvg/uwc9D/src/Rsvg.jl:5
> ERROR: LoadError: Failed to precompile Rsvg [c4c386cf-5103-5370-be45-f3a111cca3b8] to /Users/George/.julia/compiled/v1.1/Rsvg/aWLhH.ji.
> Stacktrace:
>  [1] error(::String) at ./error.jl:33
>  [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1197
>  [3] _require(::Base.PkgId) at ./loading.jl:960
>  [4] require(::Base.PkgId) at ./loading.jl:858
>  [5] require(::Module, ::Symbol) at ./loading.jl:853
>  [6] include at ./boot.jl:326 [inlined]
>  [7] include_relative(::Module, ::String) at ./loading.jl:1038
>  [8] include(::Module, ::String) at ./sysimg.jl:29
>  [9] top-level scope at none:2
>  [10] eval at ./boot.jl:328 [inlined]
>  [11] eval(::Expr) at ./client.jl:404
>  [12] top-level scope at ./none:3
> in expression starting at /Users/George/.julia/packages/VariantVisualization/cbN7w/src/VariantVisualization.jl:6
>

**Comment by lobingera** [comment]
My general comment on Homebrew/BinDeps problems usually is: Install the library manually and use a deps/deps.jl to point to the library. Do you use Rsvg alone or do you pass to Cairo?

**Comment by gtollefson** [comment]
@lobingera I'm not exactly sure how to do that... I'll read up. Can you tell me if it looks like this will affect other users who try to install our package that depends on Rsvg?

We've built a Julia package for data visualization that uses both Rsvg and Cairo to support our plotting functions that are built using PlotlyJS.jl functions. Both Rsvg and Cairo fail to build for me and I'm concerned that this will affect other users.

 I've tried wiping Julia and reinstalling Rsvg and now get the following error message:

> Building Rsvg ─────→ `~/.julia/packages/Rsvg/uwc9D/deps/build.log`
> ┌ Error: Error building `Rsvg`: 
> │ Error: glib: undefined method `uses_from_macos' for Formulary::FormulaNamespace4ff9cd134b033db5870ae4d7ca9f06e7::Glib:Class
> │ ERROR: LoadError: ArgumentError: `brew info` failed for ["cairo", "gdk-pixbuf", "glib", "libcroco", "pango"]!
> │ Stacktrace:
> │  [1] json(::Array{String,1}) at /Users/George/.julia/packages/Homebrew/s09IX/src/API.jl:192
> │  [2] info(::Array{String,1}) at /Users/George/.julia/packages/Homebrew/s09IX/src/API.jl:229
> │  [3] #direct_deps#10(::Bool, ::Function, ::String) at /Users/George/.julia/packages/Homebrew/s09IX/src/API.jl:285
> │  [4] #direct_deps at ./none:0 [inlined]
> │  [5] #deps_tree#17(::Bool, ::Function, ::String) at /Users/George/.julia/packages/Homebrew/s09IX/src/API.jl:306
> │  [6] #deps_tree at ./tuple.jl:0 [inlined]
> │  [7] #deps_sorted#24(::Bool, ::Function, ::String) at /Users/George/.julia/packages/Homebrew/s09IX/src/API.jl:379
> │  [8] deps_sorted at /Users/George/.julia/packages/Homebrew/s09IX/src/API.jl:379 [inlined]
> │  [9] #add#29(::Bool, ::Bool, ::Function, ::String) at /Users/George/.julia/packages/Homebrew/s09IX/src/API.jl:420
> │  [10] add at /Users/George/.julia/packages/Homebrew/s09IX/src/API.jl:412 [inlined]
> │  [11] install(::Array{String,1}) at /Users/George/.julia/packages/Homebrew/s09IX/src/bindeps_integration.jl:50
> │  [12] (::getfield(Homebrew, Symbol("##80#81")))() at /Users/George/.julia/packages/Homebrew/s09IX/src/bindeps_integration.jl:45
> │  [13] run(::getfield(Homebrew, Symbol("##80#81"))) at /Users/George/.julia/packages/BinDeps/ZEval/src/BinDeps.jl:478
> │  [14] run(::BinDeps.SynchronousStepCollection) at /Users/George/.julia/packages/BinDeps/ZEval/src/BinDeps.jl:521
> │  [15] satisfy!(::BinDeps.LibraryDependency, ::Array{DataType,1}) at /Users/George/.julia/packages/BinDeps/ZEval/src/dependencies.jl:944
> │  [16] satisfy!(::BinDeps.LibraryDependency) at /Users/George/.julia/packages/BinDeps/ZEval/src/dependencies.jl:922
> │  [17] top-level scope at /Users/George/.julia/packages/BinDeps/ZEval/src/dependencies.jl:977
> │  [18] include at ./boot.jl:326 [inlined]
> │  [19] include_relative(::Module, ::String) at ./loading.jl:1038
> │  [20] include(::Module, ::String) at ./sysimg.jl:29
> │  [21] include(::String) at ./client.jl:403
> │  [22] top-level scope at none:0
> │ in expression starting at /Users/George/.julia/packages/Rsvg/uwc9D/deps/build.jl:33
> └ @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075

**Comment by gtollefson** [comment]
I question I'm more interested in is, how do bindeps/homebrew issues arise? How common can we expect this to be in our user base? We've built a command line tool that is powered by our Julia package that's meant to be used by "non-programmer" users who won't be able to debug/rebuild packages.

**Comment by lobingera** [comment]
To the above question how to do a manual path set:
```
bi@orange4:~/.julia/dev/Rsvg$ cat deps/deps.jl 
# This is an auto-generated file; do not edit and do not check-in to version control

# Pre-hooks

if VERSION >= v"0.7.0-DEV.3382"
    using Libdl
end
# Macro to load a library
macro checked_lib(libname, path)
    if Libdl.dlopen_e(path) == C_NULL
        error("Unable to load \n\n$libname ($path)\n\nPlease ",
              "re-run Pkg.build(package), and restart Julia.")
    end
    quote
        const $(esc(libname)) = $path
    end
end

# Load dependencies
@checked_lib libgio "/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0"
@checked_lib librsvg "/usr/lib/x86_64-linux-gnu/librsvg-2.so.2"

# Load-hooks
```

You need to take/make a file like this and replace the autogenerated paths with your path to libraries.

To the lower question, what to expect form BinDeps/Homebrew. The issues are all tied to mismatches between Homebrew itself, the Homebrew.jl and the setting in the package recipe for BinDeps. An additional problem in the meanwhile is, that BinDeps tests availability of libraries by opening them and some libraries in the gnome environement (gtk, glib etc.) this is a problem, as they are not built to be opened twice (one testing, two using). I'd recommend a question on discourse (or slack) to get a picture, what other people expect as progress on that. 
I personally don't have windows and MacOS available and my package (and my work on Cairo) expected the binary dependencies problem as solved. I'm happy to pick up solutions other user propose on isssues or PRs. A group of people (inlc. @davidanthoff ) discussed pre-juliacon about looking at this issue F2F in the hackathon day of the juliacon, but i haven't seen updates.
