### ISSUE TITLE
prepare 0.0.2

### ISSUE THREAD

**Issue by lobingera** [lobingera/Rsvg.jl#4]
- [x] git tag correctly, 0.0.1 git tag is visible -> see https://github.com/lobingera/Rsvg.jl/releases
- [x] osx homebrew require
- [x] travis badge
- [ ] testing on 0.4/0.5
- [x] add Windows BinDeps

**Comment by sglyon** [comment]
Could we add Windows support to the list?

I don't use windows myself (or even have access to a windows box), but if Rsvg.jl is a dependency of my package it would be great if it had windows support.

**Comment by lobingera** [comment]
similar to the OSX/Homebrew: Unfortunately i don't have a Windows box (for development) available, so i can copy a setup of BinDeps but can't really test.

**Comment by sglyon** [comment]
Ok that sounds good.

I'm on OS X and can confirm that the home-brew setup currently in build.jl works. 

I can ask a friend to test out the windows setup once we have a BinDeps stub for that.

**Comment by lobingera** [comment]
i'm trying to get WinRPM running locally, to have some idea about dependencies. Unfortunately librsvg has a lot of it...
And then i ran into a WinRPM problem
https://github.com/JuliaLang/WinRPM.jl/issues/75

**Comment by lobingera** [comment]
@spencerlyon2 if you could ask someone for testing, it'd be nice. I just added the simple WinRPM-provide definition. Hope that packagemanagement finds the dependencies. 
https://github.com/lobingera/Rsvg.jl/commit/b338f4aa8bacc05343ca087f9764dc73f8e3cd7f

**Comment by sglyon** [comment]
@lobingera thanks will do. I'll see if someone can try it out on Monday

**Comment by sglyon** [comment]
Ok so it didn't work at first because `librsvg-2-2` wasn't added as an alias within your call to `library_dependecy`. 

After adding that it worked for me.

**Comment by sglyon** [comment]
ping.

Any chance we can tag a new version with windows support?

**Comment by lobingera** [comment]
I've just seen the package evaluation report, 0.5 is still failing. I'll look into it tomorrow, i guess. Tag should come soon.

**Comment by sglyon** [comment]
PkgEvaluator.jl has been having lots of issues on 0.5. Do we need to wait for it, or could we try to use Travis ourselves?

**Comment by lobingera** [comment]
i ran locally on 0.5.0-dev+4096 and i'm waiting for some appveyor results. OSX on travis needs something as we need xvfb and 0.5 generally has issues imported from Cairo/Gtk.

**Comment by lobingera** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/5263

**Comment by sglyon** [comment]
Thank you!

**Comment by lobingera** [comment]
Tony  recommended to put the Windows requirements into REQUIRE correctly. I'll look at this when I'm back at my development machine.

**Comment by lobingera** [comment]
I cannot fully agree on testing 0.4/0.5, this will be part of a next release.
